apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-devops-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-devops-app
  template:
    metadata:
      labels:
        app: weather-devops-app
    spec:
      containers:
        - name: weather-devops-container
          image: weather-devops-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
