name: Weather App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Check application files
        run: |
          ls
          test -f server.js
          test -f Dockerfile
          test -f Jenkinsfile

      - name: Build Docker image
        run: docker build -t weather-devops-app .

      - name: Show Docker images
        run: docker images
